### ISSUE TITLE
Doesn't work on Sketch Version 3.3.1 (12002).

### ISSUE THREAD

**Issue by djjedclash** [jamztang/MagicMirror#12]
OS El Capitan. Please help! If you need some additional info - ready to help!

**Comment by jamztang** [comment]
Hi @djjedclash I've never been supporting version prior to 3.3.3, maybe you can update to Sketch 3.4?

**Comment by djjedclash** [comment]
Thank you! This was my bad. Everything work in last version!

**Comment by robdomfer** [comment]
Doesn't work for me, and i have 3.5 versión... :(

**Comment by jamztang** [comment]
Did you update to Magic Mirror 2 @robdomfer ?

**Comment by robdomfer** [comment]
@jamztang Yes, I have the last version :+1: But i can't use the plugin, i'll try to solve, or find out what happens.
