### ISSUE TITLE
Can't make it run in Sketch 3.3

### ISSUE THREAD

**Issue by reznik** [jamztang/MagicMirror#13]
... But works fine in Sketch 3.4 beta

**Comment by jamztang** [comment]
v1.3 and v1.2 supports 3.3.3

**Comment by reznik** [comment]
So, looks like I have wrong Sketch v.3.3.3:-) I've downloaded previous version (committed Aug 20) — works fine.

**Comment by jamztang** [comment]
v3.5 is out, closing this issue for now
