### ISSUE TITLE
Images are always distorted and rotated

### ISSUE THREAD

**Issue by andyra** [jamztang/MagicMirror#14]
Whenever I use Magic Mirror, the resulting image is always rotated (sometimes 90°, sometimes 180°) and distorted:
![screen shot 2015-11-16 at 1 11 35 pm](https://cloud.githubusercontent.com/assets/784440/11191952/f69e2cc6-8c63-11e5-9530-a3b49d6fa027.png)

Whenever I select the shape layer with the distorted image fill and select Magic Mirror > Rotate Content, nothing happens. When I try rotating the artboard 90°, the image is positioned correctly but still maintains that weird blurry, stretched-out look.
![screen shot 2015-11-16 at 1 17 21 pm](https://cloud.githubusercontent.com/assets/784440/11192072/8d57aab6-8c64-11e5-9af9-962eebeb07e6.png)

I'm running the latest version of Magic Mirror with Sketch 3.4.2 on OS X 10.11.1

**Comment by jamztang** [comment]
Does your shape contains rounded corners? If that's the case you will have to either use get the license and use the beta version, or simply add a mask
