### ISSUE TITLE
Distorted Image

### ISSUE THREAD

**Issue by laurencollins** [jamztang/MagicMirror#15]
Hi!

When I use the magic mirror plugin, the image becomes blurry and completely distorted. Not sure what's going on. I tried reinstalling the plugin but the same issue happens. This is in Sketch v3.4.2

![device](https://cloud.githubusercontent.com/assets/5931269/11365479/2dfe72ea-92a7-11e5-8a9d-8d4af6c1e860.png)

**Comment by jamztang** [comment]
Would it be because the shape later contains corner radius? V1.2.x doesn't support that yet

**Comment by laurencollins** [comment]
Unfortunately the shape layer I was using had no corner radius. It looks like there is, but that is a different later behind the shape layer.

**Comment by jamztang** [comment]
Is there a Sketch file that you can share with us that demonstrates the issue?

**Comment by jamztang** [comment]
[Magic Mirror 2](http://magicmirror.design) has better transforming algorithm, may have fixed the issue, please let me know if everything works, cheers!
