### ISSUE TITLE
Can't seem to figure out Magic Mirror 2

### ISSUE THREAD

**Issue by navneetnair** [jamztang/MagicMirror#17]
Is there a video that explains how it works?

**Comment by navneetnair** [comment]
I'm not sure if it is an issue with Version 3.5 (25232) I seem to be doing everything the tutorial tells me to...

**Comment by Ere00** [comment]
Hello 

Same here, I have artboard named "A" inside it has blue rectangle. Then i have another artboard named "B" that has a rectangle with transformation in side it. I have named it "A" then /magic mirror/ , it does not do anything. 

It do not give any errors it just do not move the A artboard content to transfomed layer. 

I have Sketch version 3.5 (25232)

**Comment by navneetnair** [comment]
The older plugin was working yesterday. I downloaded the new plugin and also updated Sketch to 3.5. I even tried reinstalling the old plugin. Even that does not work with 3.5. Looks like there is a compatibility issue here...

**Comment by Ere00** [comment]
Ah good to know that others have had same issues, well maybe they will fix it soon.

**Comment by jamztang** [comment]
We have fixed issues with Sketch 3.5, please just re-download from the [website](http://magicmirror.design) and let me know if anything!
