### ISSUE TITLE
Compatibility issues Sketch Version 3.5 (25232)

### ISSUE THREAD

**Issue by Ere00** [jamztang/MagicMirror#18]
Example: 

*** Brought to own issue from Can't seem to figure out Magic Mirror 2 issue ***
 
I have artboard named "A" inside it has a blue rectangle. Then I have another artboard named "B" that has a rectangle with transformation inside it. I have named it "A" then /magic mirror/ , it does not do anything.

It does not give any errors it just does not move the A artboard content to transformed layer.

I have Sketch version 3.5 (25232)
Newest plugin version.

**Comment by jpaw61** [comment]
I'm running into the same issue. I was running the old version of the plugin and it wouldn't work on sketch 3.5. I also updated the plugin and it still wouldn't work.

**Comment by Ere00** [comment]
I think the version 2 fixed the problem though needed to install plugin manually not with sketch toolbox.

**Comment by jpaw61** [comment]
Thanks! I downloaded it and I'll give it a shot this afternoon.

**Comment by jamztang** [comment]
Thanks guys, latest version 2.0.1 should have fixed issues with 3.5, can be both downloaded from website and Sketch Toolbox, please let me know if running into issues!
