### ISSUE TITLE
Not Working in Sketch 3.6 

### ISSUE THREAD

**Issue by HardcoreIOS** [jamztang/MagicMirror#23]
I have been trying to use magic mirror in sketch 3.6 but it isn't working :(

**Comment by Gogoro** [comment]
I got the same problem myself. I downloaded Sketch 3.5.1 and it works fine for now. 

Link to download: http://www.sketchapp.com/download/sketch-3.5.1.zip

**Comment by jamztang** [comment]
New version has been out, please download v2.0.3 on the website http://magicmirror.design cheers!

**Comment by HardcoreIOS** [comment]
> On Mar 2, 2016, at 8:27 AM, James Tang <notifications@github.com> wrote:
> 
> New version has been out, please download v2.0.3 on the website http://magicmirror.design <http://magicmirror.design/> cheers!
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/jamztang/MagicMirror/issues/23#issuecomment-191237703>.
> 
Alright thanks for updating but,,, I found one problem in the plugin. When I press control shift m nothing happens :( I even tried doing it manually by clicking the enable/disable button but nothing is happening. it’s not working

**Comment by HardcoreIOS** [comment]
> On Mar 2, 2016, at 8:27 AM, James Tang <notifications@github.com> wrote:
> 
> New version has been out, please download v2.0.3 on the website http://magicmirror.design <http://magicmirror.design/> cheers!
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/jamztang/MagicMirror/issues/23#issuecomment-191237703>.
> 
I have created a video of the problem please watch :) http://quick.as/326vuox71 <http://quick.as/326vuox71>

**Comment by HardcoreIOS** [comment]
> On Mar 2, 2016, at 8:27 AM, James Tang <notifications@github.com> wrote:
> 
> New version has been out, please download v2.0.3 on the website http://magicmirror.design <http://magicmirror.design/> cheers!
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/jamztang/MagicMirror/issues/23#issuecomment-191237703>.
> 
NOTE: This happened after i updated it

**Comment by jamztang** [comment]
Would it happen that your are installing via Sketch toolbox? If that's the case, please uninstall from toolbox and download directly.

I also have a trouble shoot guide to describe some rarer cases, please refer and let me know https://github.com/jamztang/MagicMirror/wiki/Troubleshooting

**Comment by HardcoreIOS** [comment]
I never used sketch toolbox, I downloaded it directly!

**Comment by jamztang** [comment]
Please follow this guide and see if things work? 
https://github.com/jamztang/MagicMirror/wiki/Command-Line-Deregister

**Comment by HardcoreIOS** [comment]
> On Mar 2, 2016, at 9:28 AM, James Tang <notifications@github.com> wrote:
> 
> Please follow this guide and see if things work? 
> https://github.com/jamztang/MagicMirror/wiki/Command-Line-Deregister <https://github.com/jamztang/MagicMirror/wiki/Command-Line-Deregister>
> —
> Reply to this email directly or view it on GitHub <https://github.com/jamztang/MagicMirror/issues/23#issuecomment-191259448>.
> 
It didn’t help. In fact I re-downloaded the plugin and ran the code in the run custom plugin. When I press Run this is all I get

**Comment by HardcoreIOS** [comment]
> On Mar 2, 2016, at 9:28 AM, James Tang <notifications@github.com> wrote:
> 
> Please follow this guide and see if things work? 
> https://github.com/jamztang/MagicMirror/wiki/Command-Line-Deregister <https://github.com/jamztang/MagicMirror/wiki/Command-Line-Deregister>
> —
> Reply to this email directly or view it on GitHub <https://github.com/jamztang/MagicMirror/issues/23#issuecomment-191259448>.
> 
still isn’t working :(

**Comment by jamztang** [comment]
Would appreciate your help to retrieve the crash log for me https://github.com/jamztang/MagicMirror/wiki/Retrieving-Crash-Log

**Comment by HardcoreIOS** [comment]
> On Mar 2, 2016, at 10:28 AM, James Tang <notifications@github.com> wrote:
> 
> Would appreciate your help to retrieve the crash log for me https://github.com/jamztang/MagicMirror/wiki/Retrieving-Crash-Log <https://github.com/jamztang/MagicMirror/wiki/Retrieving-Crash-Log>
> —
> Reply to this email directly or view it on GitHub <https://github.com/jamztang/MagicMirror/issues/23#issuecomment-191287487>.
> 
I am still stuck. The plugin isn’t working :(

**Comment by jamztang** [comment]
You can attach the crash log here so that we can  take a look

**Comment by HardcoreIOS** [comment]
<img width="835" alt="screen shot 2016-03-02 at 11 02 22 am" src="https://cloud.githubusercontent.com/assets/15222571/13467574/d6d009ac-e06c-11e5-9775-8b5b6c0b9a03.png">

**Comment by jamztang** [comment]
Never seen that before. It looks like theres something hanging around. Do you have more than a couple if sketch Windows opened? I would suggest to close others and do a system reboot first.

**Comment by HardcoreIOS** [comment]
> On Mar 2, 2016, at 12:01 PM, James Tang <notifications@github.com> wrote:
> 
> Never seen that before. It looks like theres something hanging around. Do you have more than a couple if sketch Windows opened? I would suggest to close others and do a system reboot first.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/jamztang/MagicMirror/issues/23#issuecomment-191326306>.
> 
I only have one window opened. And I re-booted it and tried again but isn’t working. Have you updated it for sketch 3.6?

**Comment by jamztang** [comment]
Yes plugin version 2.0.3 should work on Sketch 3.6, I am thinking if that was something else. Would you mind follow the last step of the Crash Log Retrieval Guide so that we can get the text format of the crash log?

**Comment by HardcoreIOS** [comment]
> On Mar 3, 2016, at 8:52 AM, James Tang <notifications@github.com> wrote:
> 
> Yes plugin version 2.0.3 should work on Sketch 3.6, I am thinking if that was something else. Would you mind follow the last step of the Crash Log Retrieval Guide so that we can get the text format of the crash log?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/jamztang/MagicMirror/issues/23#issuecomment-191767633>.
> 
I fixed by installing sketch 3.6.1

**Comment by jamztang** [comment]
Thanks @HardcoreIOS, glad we get through it!
