### ISSUE TITLE
Magic mirror still does not work after reinstalling and trouble shooting everything.. 

### ISSUE THREAD

**Issue by Gorbax9** [jamztang/MagicMirror#24]
I uninstalled it and reinstalled it directly from the website and rebooted everything and nothing works. Did I miss something? 

Im running version 3.6.1 on Sketch 

Also, the site says: "Essential image transform tool for Sketch 3.5" This means 3.5 and up right? Otherwise it would be crazy if I had to downgrade a version just so I can use this plugin... Someone help. Thank you.

**Comment by Gorbax9** [comment]
**UPDATE: I got it to work!**

Follow these exact steps! 

(assuming you have deleted or uninstalled the current version)

1. download the file from the site: http://magicmirror.design/

2. find the folder

3. In Sketch. Go under the 'Plugins' menu on the top and go to 'Manage Plugins' 

4. click on the bottom arrow icon at the bottom and scroll down to: "Show Plugins Folder"

5. go back to #2 where you have the new version folder and drag that entire folder manually-- into the main "Plugins" folder and then make a sandwich

6. eat the sandwich and boom. It should work now. :)

**Comment by jamztang** [comment]
@Gorbax9 Thanks for the heads up! I have definitely forget about the folder thing. I'll add it to the wiki now!

**Comment by Gorbax9** [comment]
no worries @jamztang. :)

**Comment by jamztang** [comment]
I've updated the [troubleshooting guide](https://github.com/jamztang/MagicMirror/wiki/Troubleshooting) and [step by step uninstall manually](https://github.com/jamztang/MagicMirror/wiki/Uninstall-Manually)

Thanks @Gorbax9 !
