### ISSUE TITLE
Doesn't work on Sketch Version 3.3.3 (12081) non MAS on Mavericks 10.9.5

### ISSUE THREAD

**Issue by tschundeee** [jamztang/MagicMirror#3]
I tried you prepared test file and also some experiments on my own. It simpl does nothing. Any clue what is wrong here?

**Comment by jamztang** [comment]
Hi @tschundeee, this is my config:

Yosemite 10.10.4
Sketch is Version 3.3.3 (12072)

I think could be the version of OS resulting in a different API call. Would you try take a look at the Console and see any errors occurred from Sketch?

**Comment by rwam** [comment]
Same behavior here. Sketch Version 3.3.3 on Mavericks 10.9.5. It doesn't work ;(

Here some debugging infos for you:

```


Aug  3 14:18:44 mysterion Magic Mirror! (Sketch Plugin)[7540]: Caught script exception: *** -[__NSArrayM objectAtIndex:]: index 242 beyond bounds [0 .. 23]
Aug  3 14:18:49 mysterion Jump To Artboard (Sketch Plugin)[7540]: Caught script exception: *** -[__NSArrayM objectAtIndex:]: index 242 beyond bounds [0 .. 23]
Aug  3 14:18:58 mysterion Rotate Points (Sketch Plugin)[7540]: Caught script exception: *** -[__NSArrayM objectAtIndex:]: index 242 beyond bounds [0 .. 23]
```

**Comment by jamztang** [comment]
Thanks for the crash log, it indicates some array issues which could potentially happens all over the flow, that would be something I need to sit down in front of a Mavericks computer and break down the application logic manually to find out and fix

**Comment by jamztang** [comment]
Guys, would you download this latest version if see if there's any issues with it?

**Comment by rwam** [comment]
Hi @jamztang,

it works without any issues. Thank you for your fast response.

**Comment by jamztang** [comment]
Consider donating if you like it :)

**Comment by jamztang** [comment]
reopen until it's merged in next release

**Comment by tschundeee** [comment]
I migrated to Yosemite and now it works. Already donated :+1: Thx for your support

**Comment by jamztang** [comment]
Awesome, appreciate your donation!
