### ISSUE TITLE
New version of Sketch and red lines

### ISSUE THREAD

**Issue by duttyfree** [jamztang/MagicMirror#33]
hey! good mornings, 
i just update to new sketch, and have a brand new use of symbols that make MagicMirroring fill the artboard with 45º red lines, i suppose that because can´t find nothing to show.
![captura de pantalla 2016-04-13 a las 12 55 25](https://cloud.githubusercontent.com/assets/5617533/14491086/08ba038e-0177-11e6-82dc-51ce82de385c.png)

**Comment by rgesulfo** [comment]
Same issue.

**Comment by sogen** [comment]
Same here

**Comment by jamztang** [comment]
I've pushed an update specifically to address this issue in v2.0.6!

**Comment by rgesulfo** [comment]
Thanks a lot for your speed!

**Comment by duttyfree** [comment]
Thanke so much! the best new in this monday! 💃
