### ISSUE TITLE
3.7 Support?

### ISSUE THREAD

**Issue by rorysmyth** [jamztang/MagicMirror#35]
Are you planning to support symbols and nested symbols?

**Comment by sogen** [comment]
Symbols work fine with latest update

**Comment by rorysmyth** [comment]
Not for me

![image](https://cloud.githubusercontent.com/assets/1512382/14645923/8a980ad6-064f-11e6-8d7a-e02b941714ae.png)

**Comment by thierryc** [comment]
I have the same Issue on pro version.

**Comment by jamztang** [comment]
Symbols should be fixed already in 2.0.6, After update please restart Sketch!

**Comment by thierryc** [comment]
Thank you!
