### ISSUE TITLE
Blurriness

### ISSUE THREAD

**Issue by rorysmyth** [jamztang/MagicMirror#4]
The copy always comes out a bit blurry. Any way of fixing this?

![image](https://cloud.githubusercontent.com/assets/1512382/9006971/cf957672-3784-11e5-9c0c-f0b28f246763.png)

**Comment by jamztang** [comment]
I will make a note on optimising the image quality.
Does that happen when you export? There're a few issues with layer fill previewing in Sketch

**Comment by rorysmyth** [comment]
Hey, yeah it's still blurry when i export

**Comment by jamztang** [comment]
Yes it's, I am working out a solution for that, probably be there next version!

**Comment by rorysmyth** [comment]
Great stuff. So if i'm working in 1x and I export an artboard, will the magic mirror layer scale up too? Would be a great feature for the designers who work at 1x.

Just donated. Great product!

**Comment by jamztang** [comment]
Appreciate for the donation!The scale up thing would be tricky. I can think of a possible solution if we are mirroring a 1x art board to a 2x shape, but have to find out how it'd work out for export, but I am definitely working hard on this!



—

**Comment by jamztang** [comment]
The upcoming v1.2 will solve the issue!
