### ISSUE TITLE
License not working

### ISSUE THREAD

**Issue by dejvcz** [jamztang/MagicMirror#51]
I have just changed my mac for a new model, installed Sketch and also Magic Mirror and tried to enter my license code (ID of payment from PayPal) but unfortunately it has not worked and it's just say Incorrect License.

**Comment by unetics** [comment]
just purchased getting same problem is there a lag between purchase and licence activation?

**Comment by jamztang** [comment]
There's a small delay, until the system sends you an email with the correct license key, that's sent to your PayPal email address. @dejvcz @unetics can you send me your PayPal email address that I can look up to see if the email correctly delivers?

**Comment by unetics** [comment]
should be a @echoedlight.com email not sure there a re a few emails connected to the account

**Comment by unetics** [comment]
primary is  @makeweb.com.au but don't think paypal have sorted out that change yet

**Comment by jamztang** [comment]
I looked up in my system and it looks like it has successfully delivered to your @makeweb.com.au email address. Do you want me to also sent to some other email address?

**Comment by unetics** [comment]
just got it thanks

**Comment by dejvcz** [comment]
@jamztang my email address - david.kravacek@email.cz

**Comment by jamztang** [comment]
Just replied you in the email @dejvcz
