### ISSUE TITLE
Plugin not showing up in Plugins menu

### ISSUE THREAD

**Issue by amitu** [jamztang/MagicMirror#8]
I installed, first via Sketch Toolbox, then manually downloading .sketchplugin file and placing it in "Reveal Plugins Folder", and finally by double clicking on .sketchplugin (I have only one version of Sketch installed).

If it helps, I am using it with the trial version of Sketch 3.3.3 on Yos (10.10.4).

**Comment by jamztang** [comment]
I seems like installing via sketch toolbox may results that the plugin buried one folder deeper than expected. Please right click and show contents, if there's another .sketchplugin, that's the real one. Rename the containing folder to without the .sketchPlugin extension

**Comment by mischugo** [comment]
Same for me. I have installed via toolbox and by hand. I did like the description but... the plugin does not appear in the plugin list
Also, the plugmanagement in the last beta has "changed" /modified

I'm using both, Sketch 3.3.3 and the last beta on Yos 10.4.4

**Comment by jamztang** [comment]
Thanks if you're please with the plugin please consider donate :)

**Comment by jamztang** [comment]
I've submitted a patch regarding to SketchToolbox installation issue https://github.com/sketchplugins/plugin-directory/pull/133
For now before it's being merged, we'll have to install manually

**Comment by jamztang** [comment]
This should be resolved!
